theme: jekyll-theme-minimal
title: Sonny Carlton's Portfolio
description: Hello! I'm a Biomedical Engineering, Master of Engineering student graduating in May 2021 from Cornell University. I'm currently looking for a full time positon. You can contact me at: sbc229@cornell.edu.
show_downloads: false
