theme: jekyll-theme-minimal
title: Welcome to Sonny Carlton
description: A website for showcasing the work I've done primarily in terms of coding and biomedical device research. 
show_downloads: false
