theme: jekyll-theme-minimal
title: Sonny Carlton's Portfolio
description: Hello! I'm a Biomedical Engineering, Master of Engineering student graduating in May 2021 from Cornell University. I'm currently looking for a full time positon. Look at my work primarily in coding and biomedical device research. 
show_downloads: false
